### ISSUE TITLE
autogen.sh returns an error, is there another way to build without autoreconf？

### ISSUE THREAD

**Issue by soyoeml** [yzfedora/baidudl#6]
/DataVolume/shares/share/bddl/baidudl# autoreconf
/opt/share/automake-1.12/Automake/ChannelDefs.pm line 23:

This Perl hasn't been configured and built properly for the threads
module to work.  (The 'useithreads' configuration option hasn't been used.)

Having threads support requires all of Perl and all of the XS modules in
the Perl installation to be rebuilt, it is not just a question of adding
the threads module.  (In other words, threaded and non-threaded Perls
are binary incompatible.)

If you want to the use the threads module, please contact the people
who built your Perl.

Cannot continue, aborting.
BEGIN failed--compilation aborted at /opt/lib/perl5/5.8.8/ppc-linux/threads.pm line 28.
Compilation failed in require at /opt/share/automake-1.12/Automake/ChannelDefs.pm line 23.
BEGIN failed--compilation aborted at /opt/share/automake-1.12/Automake/ChannelDefs.pm line 26.
Compilation failed in require at /opt/share/automake-1.12/Automake/Configure_ac.pm line 27.
BEGIN failed--compilation aborted at /opt/share/automake-1.12/Automake/Configure_ac.pm line 27.
Compilation failed in require at /opt/bin/aclocal line 38.
BEGIN failed--compilation aborted at /opt/bin/aclocal line 38.
autoreconf: aclocal failed with exit status: 255

**Comment by yzfedora** [comment]
okay, I just made a commit, added a Makefile to the source tree. please
synchronous the repository first. then follow below steps:

you should see there is a Makefile in "baidudl/src", it's same with
Makefile.bak. for some people they didn't have GNU automake installed on
their system. try use default Makefile.

$ cd src
$ cp Makefile.bak Makefile              [required if Makefile not exists]
$ make
$ make install

**Comment by soyoeml** [comment]
It has a Makefile in src folder.  I changed some configuration and compiled successfully for embedded linux. It runs very good.

Thanks.
