### ISSUE TITLE
-n 参数无效，只能是默认的16

### ISSUE THREAD

**Issue by zhaibin18** [yzfedora/baidudl#7]
./bdpandl  -n 100 -d 8 'https://www.baidupcs.com/rest/2.0/pcs/stream?method=download&access_token=23.e9d2d9d8df1c70437ae2cd9e55748b15.2592000.1482907541.4045822070-1641135&path=%2Fapps%2Fwp2pcs%2F%E5%86%B0%E5%B7%9D%2FCarnage.Park.2016.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT%2FCarnage.Park.2016.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT.mkv'
--------------Received Meta info---------------
HTTP/1.1 200 OK
Date: Tue, 29 Nov 2016 05:14:28 GMT
Content-Type: application/octet-stream
Connection: close
x-bs-file-size: 7100830047
x-bs-meta-crc32: 1621376268
x-poms-key: 0000e1c993f7072aae0734b21fd05759a128
ETag: 509aea60d5abc46d882818f95d9cc508
x-bs-client-ip: MTExLjIwMS4wLjE2NQ==
Content-Length: 7100830047
x-bs-request-id: MTAuNTQuMjcuMjc6ODY0Mzo3NzM2MDA1OTY2OTMxNjI5NDExOjIwMTYtMTEtMjkgMTM6MTQ6Mjc=
Content-Disposition: attachment;filename="Carnage.Park.2016.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT.mkv"
Content-MD5: 509aea60d5abc46d882818f95d9cc508
superfile: 2
Accept-Ranges: bytes
Last-Modified: Fri, 04 Nov 2016 13:54:30 GMT
Server: POMS/CloudUI 1.0

--------------Received Meta info---------------
HTTP/1.1 200 OK
Date: Tue, 29 Nov 2016 05:14:28 GMT
Content-Type: application/octet-stream
Connection: keep-alive
x-bs-file-size: 7100830047
x-bs-meta-crc32: 1621376268
Cache-Control: max-age=259200
ETag: 509aea60d5abc46d882818f95d9cc508
x-bs-client-ip: MTExLjIwMS4wLjE2NQ==
Content-Length: 7100830047
x-bs-request-id: MTAuNTQuMzYuNTM6ODY0Mzo3NzM2MDA2MDE2MjQwOTQzMTc3OjIwMTYtMTEtMjkgMTM6MTQ6Mjg=
Content-Disposition: attachment;filename="Carnage.Park.2016.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT.mkv"
Content-MD5: 509aea60d5abc46d882818f95d9cc508
superfile: 2
Accept-Ranges: bytes
Last-Modified: Fri, 04 Nov 2016 13:54:30 GMT
Server: POMS/CloudUI 1.0

filename=Carnage.Park.2016.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT.mkv, length=7100830047

thread 0 starting to download range: 6389760-443801876

thread 2 starting to download range: 893992960-1331405630

thread 3 starting to download range: 1337786368-1775207507

thread 1 starting to download range: 450183168-887603753

thread 4 starting to download range: 1781596160-2219009384

thread 5 starting to download range: 2225389568-2662811261

thread 6 starting to download range: 2669199360-3106613138

thread 7 starting to download range: 3112992768-3550415015

thread 8 starting to download range: 3556802560-3994216892

thread 9 starting to download range: 4000595968-4438018769

thread 10 starting to download range: 4444405760-4881820646

thread 11 starting to download range: 4889264128-5325622523

thread 12 starting to download range: 5333073920-5769424400

thread 13 starting to download range: 5776867328-6213226277

thread 14 starting to download range: 6220677120-6657028154

thread 15 starting to download range: 6664470528-7100830046

Carnage.Park.2016.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT.mkv                                                                                                                                          6.6GiB     1.7%   2.3MiB/s  00:49:17  [16]

**Comment by yzfedora** [comment]
因为你之前下载了同一个文件，但是只下载了一部分(从线程0的输出中可以看出它并不是从0的位置开始下载，而是从6389760开始下载，
6389760之前的文件已经下载完成了
)，所以程序检测到当前目录下存在相同的文件名，然后就从这个文件中读取原来下载的记录，包括线程数(原来应该是16线程)。

你可以删除当前目录下同名的文件，然后从新运行命令开始下载。0.0

**Comment by zhaibin18** [comment]
多谢！反馈这么快，好评！
